name: Build and Upload Flask App Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Determine semantic version
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0 || echo "0.1.0")
        echo "$VERSION" > VERSION

    - name: Build artifact
      run: |
        mkdir artifact
        cp -r * artifact/
        rm -rf artifact/venv artifact/__pycache__
        cp VERSION artifact/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: flask-app-artifact
        path: artifact 